export enum ToastType {
  SUCCESS = 'SUCCESS',
  ERROR = 'ERROR',
  WARNING = 'WARNING',
  INFO = 'INFO',
  CONFIRMATION = 'CONFIRMATION',
  CANCELLATION = 'CANCELLATION',
  LOADING = 'LOADING',
  CUSTOM = 'CUSTOM'
}